# Generated by Django 3.1.1 on 2020-09-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200919_2358'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='tender_id',
        ),
        migrations.AlterField(
            model_name='tender',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
    ]
