# Generated by Django 3.1.1 on 2020-09-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20200920_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='closing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tender',
            name='publish_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('SC', 'Successful')], default='PD', max_length=2)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='owner.tender')),
            ],
        ),
    ]
