# Generated by Django 3.1.1 on 2020-09-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20200920_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='closing_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tender',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
