# Generated by Django 3.1.1 on 2020-09-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_auto_20200920_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='closing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tender',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
