# Generated by Django 3.1.1 on 2020-09-20 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200919_2358'),
        ('owner', '0007_auto_20200920_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile'),
        ),
    ]
