# Generated by Django 2.2.5 on 2020-09-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('SC', 'Successful'), ('CC', 'Cancelled')], default='PD', max_length=2),
        ),
    ]
