# Generated by Django 2.2.5 on 2020-09-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('VR', 'Vendor'), ('GM', 'Garment')], default='VR', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_num',
            field=models.IntegerField(default=0),
        ),
    ]
